name: bench-browser-tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-bench:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/grafana/grafana-bench:latest
      options: --user root # tell my waaaaiiiiii
      env:
        GRAFANA_ADDRESS: ${{ secrets.GRAFANA_ADDRESS }}
        GRAFANA_USER: ${{ secrets.GRAFANA_USER }}
        GRAFANA_PASSWORD: ${{ secrets.PASSWORD }}
        SCREENSHOT_PATH: screenshots
    steps:
      - uses: actions/checkout@v4
      - name: run bench tests
        run: |
          k6 run ./bench/list-checks.js
          grafana-bench smoke 
      - name: Archive screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshots
