name: bench-browser-tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-bench:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/grafana/grafana-bench:latest@sha256:89313d5f380727ddcbbce2abaafdc2fb16b017210c1969a9d6df65138ce7a0e8
      options: --user root # tell my waaaaiiiiii
      env:
        GRAFANA_ADDRESS: ${{ secrets.GRAFANA_ADDRESS }}
        GRAFANA_USER: ${{ secrets.GRAFANA_USER }}
        GRAFANA_PASSWORD: ${{ secrets.GRAFANA_PASSWORD }}
        SCREENSHOT_PATH: screenshots
        USE_COMPILED_TESTS: true
        TEST_PATH: bench
    steps:
      - uses: actions/checkout@v4
      - name: run bench tests
        run: |
          #k6 run ./bench/list-checks.js
          grafana-bench smoke $GRAFANA_ADDRESS $GRAFANA_USER $GRAFANA_PASSWORD all
      - name: Archive screenshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshots
