name: push tests upstream

on:
  push:
    branches:
      - main

jobs:
  send-pull-requests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          path: "local"
          sparse-checkout: |
            bench

      - name: Checkout private tools
        uses: actions/checkout@v4
        with:
          path: "api-tests"
          repository: jalevin/grafana-platform-tests
          token: ${{ secrets.JEFF_PAT }} #- name: Checkout

      - name: create PR
        run: |

          rm -rf ./api-tests/repositories/jeff-test-repo
          mkdir -p ./api-tests/repositories/jeff-test-repo
          cp -R ./local/bench ./api-tests/repositories/jeff-test-repo

          echo ROOT
          ls -lha .
          echo API-TESTS
          ls -lha ./api-tests/
          echo REPOSITORIES
          ls -lha ./api-tests/repositories
          echo TEST-REPO
          ls -lha ./api-tests/repositories/jeff-test-repo

          # create branch and add files
          cd api-tests 
          git remote set-url origin https://jalevin:${{secrets.JEFF_PAT}}@github.com/jalevin/grafana-platform-tests.git
          git checkout -b bench_bot/${{ github.repository }}/${{ github.sha }}
          git config user.email "jeff@levinology.com"
          git config user.name "jalevin"
          git add .
          git commit -m 'chore: update ${{ github.repository }} tests to latest'
          git push origin bench_bot/${{github.repository}}/${{ github.sha}}

          # create PR
          touch token.txt
          echo ${{ secrets.JEFF_PAT }} > token.txt
          ls -al
          gh auth login --with-token < token.txt
          gh pr create \
            --body "" \
            --title "chore: update tests for ${{ github.repository }}" \
            --head "bench_bot/update/${{github.repository}}/${{ github.sha}}" \
            --base "main"
          rm -f token.txt
